# proxy/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: argocd
  labels:
    id: C0904889
    app: nginx-proxy
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
        - name: nginx
          image: nginx:latest  # Build this image or use the default
          ports:
            - containerPort: 80
