# db/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: argocd
  labels:
    id: C0904889
    app: mariadb
    env: dev
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mariadb
